/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpertIndexRouteImport } from './routes/expert/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ExpertTimeSheetsRouteImport } from './routes/expert/time-sheets'
import { Route as ExpertTimeEntriesRouteImport } from './routes/expert/time-entries'
import { Route as ExpertProjectsRouteImport } from './routes/expert/projects'
import { Route as ExpertOrgsRouteImport } from './routes/expert/_orgs'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ExpertTimeSheetsIdRouteImport } from './routes/expert/time-sheets.$id'
import { Route as ExpertTimeEntriesIdRouteImport } from './routes/expert/time-entries.$id'
import { Route as ExpertProjectsIdRouteImport } from './routes/expert/projects.$id'
import { Route as ExpertOrgsOrganisationsRouteImport } from './routes/expert/_orgs.organisations'
import { Route as ExpertOrgsAccountsRouteImport } from './routes/expert/_orgs.accounts'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users.$id'
import { Route as ExpertOrgsOrganisationsIdRouteImport } from './routes/expert/_orgs.organisations.$id'
import { Route as ExpertOrgsAccountsIdRouteImport } from './routes/expert/_orgs.accounts.$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertTimeSheetsRoute = ExpertTimeSheetsRouteImport.update({
  id: '/time-sheets',
  path: '/time-sheets',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertTimeEntriesRoute = ExpertTimeEntriesRouteImport.update({
  id: '/time-entries',
  path: '/time-entries',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertProjectsRoute = ExpertProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertOrgsRoute = ExpertOrgsRouteImport.update({
  id: '/_orgs',
  getParentRoute: () => ExpertRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertTimeSheetsIdRoute = ExpertTimeSheetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExpertTimeSheetsRoute,
} as any)
const ExpertTimeEntriesIdRoute = ExpertTimeEntriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExpertTimeEntriesRoute,
} as any)
const ExpertProjectsIdRoute = ExpertProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExpertProjectsRoute,
} as any)
const ExpertOrgsOrganisationsRoute = ExpertOrgsOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => ExpertOrgsRoute,
} as any)
const ExpertOrgsAccountsRoute = ExpertOrgsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ExpertOrgsRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ExpertOrgsOrganisationsIdRoute =
  ExpertOrgsOrganisationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ExpertOrgsOrganisationsRoute,
  } as any)
const ExpertOrgsAccountsIdRoute = ExpertOrgsAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExpertOrgsAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertOrgsRouteWithChildren
  '/portal': typeof PortalRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/expert/projects': typeof ExpertProjectsRouteWithChildren
  '/expert/time-entries': typeof ExpertTimeEntriesRouteWithChildren
  '/expert/time-sheets': typeof ExpertTimeSheetsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/expert/accounts': typeof ExpertOrgsAccountsRouteWithChildren
  '/expert/organisations': typeof ExpertOrgsOrganisationsRouteWithChildren
  '/expert/projects/$id': typeof ExpertProjectsIdRoute
  '/expert/time-entries/$id': typeof ExpertTimeEntriesIdRoute
  '/expert/time-sheets/$id': typeof ExpertTimeSheetsIdRoute
  '/expert/accounts/$id': typeof ExpertOrgsAccountsIdRoute
  '/expert/organisations/$id': typeof ExpertOrgsOrganisationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/portal': typeof PortalRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/expert': typeof ExpertIndexRoute
  '/expert/projects': typeof ExpertProjectsRouteWithChildren
  '/expert/time-entries': typeof ExpertTimeEntriesRouteWithChildren
  '/expert/time-sheets': typeof ExpertTimeSheetsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/expert/accounts': typeof ExpertOrgsAccountsRouteWithChildren
  '/expert/organisations': typeof ExpertOrgsOrganisationsRouteWithChildren
  '/expert/projects/$id': typeof ExpertProjectsIdRoute
  '/expert/time-entries/$id': typeof ExpertTimeEntriesIdRoute
  '/expert/time-sheets/$id': typeof ExpertTimeSheetsIdRoute
  '/expert/accounts/$id': typeof ExpertOrgsAccountsIdRoute
  '/expert/organisations/$id': typeof ExpertOrgsOrganisationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/expert': typeof ExpertRouteWithChildren
  '/portal': typeof PortalRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/expert/_orgs': typeof ExpertOrgsRouteWithChildren
  '/expert/projects': typeof ExpertProjectsRouteWithChildren
  '/expert/time-entries': typeof ExpertTimeEntriesRouteWithChildren
  '/expert/time-sheets': typeof ExpertTimeSheetsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/expert/_orgs/accounts': typeof ExpertOrgsAccountsRouteWithChildren
  '/expert/_orgs/organisations': typeof ExpertOrgsOrganisationsRouteWithChildren
  '/expert/projects/$id': typeof ExpertProjectsIdRoute
  '/expert/time-entries/$id': typeof ExpertTimeEntriesIdRoute
  '/expert/time-sheets/$id': typeof ExpertTimeSheetsIdRoute
  '/expert/_orgs/accounts/$id': typeof ExpertOrgsAccountsIdRoute
  '/expert/_orgs/organisations/$id': typeof ExpertOrgsOrganisationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/expert'
    | '/portal'
    | '/admin/users'
    | '/expert/projects'
    | '/expert/time-entries'
    | '/expert/time-sheets'
    | '/admin/'
    | '/expert/'
    | '/admin/users/$id'
    | '/expert/accounts'
    | '/expert/organisations'
    | '/expert/projects/$id'
    | '/expert/time-entries/$id'
    | '/expert/time-sheets/$id'
    | '/expert/accounts/$id'
    | '/expert/organisations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/portal'
    | '/admin/users'
    | '/expert'
    | '/expert/projects'
    | '/expert/time-entries'
    | '/expert/time-sheets'
    | '/admin'
    | '/admin/users/$id'
    | '/expert/accounts'
    | '/expert/organisations'
    | '/expert/projects/$id'
    | '/expert/time-entries/$id'
    | '/expert/time-sheets/$id'
    | '/expert/accounts/$id'
    | '/expert/organisations/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/expert'
    | '/portal'
    | '/admin/users'
    | '/expert/_orgs'
    | '/expert/projects'
    | '/expert/time-entries'
    | '/expert/time-sheets'
    | '/admin/'
    | '/expert/'
    | '/admin/users/$id'
    | '/expert/_orgs/accounts'
    | '/expert/_orgs/organisations'
    | '/expert/projects/$id'
    | '/expert/time-entries/$id'
    | '/expert/time-sheets/$id'
    | '/expert/_orgs/accounts/$id'
    | '/expert/_orgs/organisations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExpertRoute: typeof ExpertRouteWithChildren
  PortalRoute: typeof PortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/': {
      id: '/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/time-sheets': {
      id: '/expert/time-sheets'
      path: '/time-sheets'
      fullPath: '/expert/time-sheets'
      preLoaderRoute: typeof ExpertTimeSheetsRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/time-entries': {
      id: '/expert/time-entries'
      path: '/time-entries'
      fullPath: '/expert/time-entries'
      preLoaderRoute: typeof ExpertTimeEntriesRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/projects': {
      id: '/expert/projects'
      path: '/projects'
      fullPath: '/expert/projects'
      preLoaderRoute: typeof ExpertProjectsRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/_orgs': {
      id: '/expert/_orgs'
      path: ''
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertOrgsRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/time-sheets/$id': {
      id: '/expert/time-sheets/$id'
      path: '/$id'
      fullPath: '/expert/time-sheets/$id'
      preLoaderRoute: typeof ExpertTimeSheetsIdRouteImport
      parentRoute: typeof ExpertTimeSheetsRoute
    }
    '/expert/time-entries/$id': {
      id: '/expert/time-entries/$id'
      path: '/$id'
      fullPath: '/expert/time-entries/$id'
      preLoaderRoute: typeof ExpertTimeEntriesIdRouteImport
      parentRoute: typeof ExpertTimeEntriesRoute
    }
    '/expert/projects/$id': {
      id: '/expert/projects/$id'
      path: '/$id'
      fullPath: '/expert/projects/$id'
      preLoaderRoute: typeof ExpertProjectsIdRouteImport
      parentRoute: typeof ExpertProjectsRoute
    }
    '/expert/_orgs/organisations': {
      id: '/expert/_orgs/organisations'
      path: '/organisations'
      fullPath: '/expert/organisations'
      preLoaderRoute: typeof ExpertOrgsOrganisationsRouteImport
      parentRoute: typeof ExpertOrgsRoute
    }
    '/expert/_orgs/accounts': {
      id: '/expert/_orgs/accounts'
      path: '/accounts'
      fullPath: '/expert/accounts'
      preLoaderRoute: typeof ExpertOrgsAccountsRouteImport
      parentRoute: typeof ExpertOrgsRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/expert/_orgs/organisations/$id': {
      id: '/expert/_orgs/organisations/$id'
      path: '/$id'
      fullPath: '/expert/organisations/$id'
      preLoaderRoute: typeof ExpertOrgsOrganisationsIdRouteImport
      parentRoute: typeof ExpertOrgsOrganisationsRoute
    }
    '/expert/_orgs/accounts/$id': {
      id: '/expert/_orgs/accounts/$id'
      path: '/$id'
      fullPath: '/expert/accounts/$id'
      preLoaderRoute: typeof ExpertOrgsAccountsIdRouteImport
      parentRoute: typeof ExpertOrgsAccountsRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExpertOrgsAccountsRouteChildren {
  ExpertOrgsAccountsIdRoute: typeof ExpertOrgsAccountsIdRoute
}

const ExpertOrgsAccountsRouteChildren: ExpertOrgsAccountsRouteChildren = {
  ExpertOrgsAccountsIdRoute: ExpertOrgsAccountsIdRoute,
}

const ExpertOrgsAccountsRouteWithChildren =
  ExpertOrgsAccountsRoute._addFileChildren(ExpertOrgsAccountsRouteChildren)

interface ExpertOrgsOrganisationsRouteChildren {
  ExpertOrgsOrganisationsIdRoute: typeof ExpertOrgsOrganisationsIdRoute
}

const ExpertOrgsOrganisationsRouteChildren: ExpertOrgsOrganisationsRouteChildren =
  {
    ExpertOrgsOrganisationsIdRoute: ExpertOrgsOrganisationsIdRoute,
  }

const ExpertOrgsOrganisationsRouteWithChildren =
  ExpertOrgsOrganisationsRoute._addFileChildren(
    ExpertOrgsOrganisationsRouteChildren,
  )

interface ExpertOrgsRouteChildren {
  ExpertOrgsAccountsRoute: typeof ExpertOrgsAccountsRouteWithChildren
  ExpertOrgsOrganisationsRoute: typeof ExpertOrgsOrganisationsRouteWithChildren
}

const ExpertOrgsRouteChildren: ExpertOrgsRouteChildren = {
  ExpertOrgsAccountsRoute: ExpertOrgsAccountsRouteWithChildren,
  ExpertOrgsOrganisationsRoute: ExpertOrgsOrganisationsRouteWithChildren,
}

const ExpertOrgsRouteWithChildren = ExpertOrgsRoute._addFileChildren(
  ExpertOrgsRouteChildren,
)

interface ExpertProjectsRouteChildren {
  ExpertProjectsIdRoute: typeof ExpertProjectsIdRoute
}

const ExpertProjectsRouteChildren: ExpertProjectsRouteChildren = {
  ExpertProjectsIdRoute: ExpertProjectsIdRoute,
}

const ExpertProjectsRouteWithChildren = ExpertProjectsRoute._addFileChildren(
  ExpertProjectsRouteChildren,
)

interface ExpertTimeEntriesRouteChildren {
  ExpertTimeEntriesIdRoute: typeof ExpertTimeEntriesIdRoute
}

const ExpertTimeEntriesRouteChildren: ExpertTimeEntriesRouteChildren = {
  ExpertTimeEntriesIdRoute: ExpertTimeEntriesIdRoute,
}

const ExpertTimeEntriesRouteWithChildren =
  ExpertTimeEntriesRoute._addFileChildren(ExpertTimeEntriesRouteChildren)

interface ExpertTimeSheetsRouteChildren {
  ExpertTimeSheetsIdRoute: typeof ExpertTimeSheetsIdRoute
}

const ExpertTimeSheetsRouteChildren: ExpertTimeSheetsRouteChildren = {
  ExpertTimeSheetsIdRoute: ExpertTimeSheetsIdRoute,
}

const ExpertTimeSheetsRouteWithChildren =
  ExpertTimeSheetsRoute._addFileChildren(ExpertTimeSheetsRouteChildren)

interface ExpertRouteChildren {
  ExpertOrgsRoute: typeof ExpertOrgsRouteWithChildren
  ExpertProjectsRoute: typeof ExpertProjectsRouteWithChildren
  ExpertTimeEntriesRoute: typeof ExpertTimeEntriesRouteWithChildren
  ExpertTimeSheetsRoute: typeof ExpertTimeSheetsRouteWithChildren
  ExpertIndexRoute: typeof ExpertIndexRoute
}

const ExpertRouteChildren: ExpertRouteChildren = {
  ExpertOrgsRoute: ExpertOrgsRouteWithChildren,
  ExpertProjectsRoute: ExpertProjectsRouteWithChildren,
  ExpertTimeEntriesRoute: ExpertTimeEntriesRouteWithChildren,
  ExpertTimeSheetsRoute: ExpertTimeSheetsRouteWithChildren,
  ExpertIndexRoute: ExpertIndexRoute,
}

const ExpertRouteWithChildren =
  ExpertRoute._addFileChildren(ExpertRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExpertRoute: ExpertRouteWithChildren,
  PortalRoute: PortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
